apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: hello 
  namespace: default 
  labels:
    application: hello 
spec:
  replicas: 3
  selector:
    matchLabels:
      application: hello 
  template:
    metadata:
      labels:
        application: hello 
    spec:
      containers:
        - name: hello 
          image: gouthamve/ingress-hello-demo:v2.1 
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello 
  namespace: default 
  labels:
    application: hello 
spec:
  type: NodePort
  selector:
    application: hello 
  ports:
  - port: 8080
    targetPort: 8080 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello 
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "ingress.local"
    http:
      paths:
      - path: /
        backend:
          serviceName: hello 
          servicePort: 8080
